name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-backend:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

       # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run build of the application
      # TODO: Add build for each services
      # - name: Run build
      #  run: go build . 

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet .
          golint .

      # Run testing on the code
      # - name: Run testing
       # run: cd test && go test -v
